### ISSUE TITLE
Cannot find -lbz2: No such file or directory

### ISSUE THREAD

**Issue by ToriFae** [cositools/cosi-setup#12]
This issue may just be the same as the other library issue above. In either case, here is the basic error:

```
Compiling MUnitTest.cxx ...
Dictionary done ...
Compiling dictionary ...
Linking libCommonMisc ...
/usr/bin/ld: cannot find -lbz2: No such file or directory
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:162: /mnt/y/SSL/COSI/COSItools/megalib/lib/libCommonMisc.so] Error 1
make[2]: *** [Makefile:12: all] Error 2
make[1]: *** [Makefile:24: glo] Error 2
make: *** [Makefile:105: glo] Error 2
```

I have attached the error log.
[Build_20241028-120205.log](https://github.com/user-attachments/files/17562186/Build_20241028-120205.log)

**Comment by zoglauer** [comment]
sudo apt install libbz2-dev

**Comment by ToriFae** [comment]
This solution did work and got me past that problem. I will note that libbz2 was already installed. It would be nice if we didn't require the DEV libraries.  

@zoglauer : Can you please assign this issue to yourself?  I am not sure if you want to close it out or if you want to make an adjustment to the install script to include libbz2-dev as a requirement.

**Comment by ToriFae** [comment]
Closing this issue as a duplicate of another issue:
[https://github.com/cositools/cosi-setup/issues/7#issue-2612691314](url)

**Comment by zoglauer** [comment]
Fixed in dc/dc3.

**Comment by JarredMRoberts** [comment]
I ran into this issue with a COSItools install on 6/17/25. Installing libbz2-dev then rerunning fixed the error and COSItools installed successfully.

**Comment by zoglauer** [comment]
Which platform was this? ubuntu?
