### ISSUE TITLE
Failed to build MEGAlib - nuclearizer - no member named IsPositiveStrip

### ISSUE THREAD

**Issue by ToriFae** [cositools/cosi-setup#13]
`
make[1]: Entering directory '/mnt/y/SSL/COSI/COSItools/nuclearizer'
Compiling MGUIEModule.cxx ...
Compiling MGUIExpo.cxx ...
Compiling MGUIExpoCombinedViewer.cxx ...
Compiling MGUIExpoSupervisor.cxx ...
Compiling MGUIMainFretalon.cxx ...
Compiling MGUIModuleSelector.cxx ...
In file included from /mnt/y/SSL/COSI/COSItools/nuclearizer/include/MReadOutAssembly.h:28,
                 from /mnt/y/SSL/COSI/COSItools/megalib/include/MModule.h:35,
                 from /mnt/y/SSL/COSI/COSItools/megalib/include/MGUIEModule.h:27,
                 from /mnt/y/SSL/COSI/COSItools/megalib/src/fretalon/framework/src/MGUIEModule.cxx:27:
/mnt/y/SSL/COSI/COSItools/nuclearizer/include/MStripHit.h: In member function ‘void MStripHit::IsXStrip(bool)’:
/mnt/y/SSL/COSI/COSItools/nuclearizer/include/MStripHit.h:62:57: error: ‘class MReadOutElementDoubleStrip’ has no member named ‘IsPositiveStrip’
   62 |   void IsXStrip(bool PositiveStrip) { m_ReadOutElement->IsPositiveStrip(PositiveStrip); }
      |                                                         ^~~~~~~~~~~~~~~
/mnt/y/SSL/COSI/COSItools/nuclearizer/include/MStripHit.h: In member function ‘bool MStripHit::IsXStrip() const’:
/mnt/y/SSL/COSI/COSItools/nuclearizer/include/MStripHit.h:64:52: error: ‘class MReadOutElementDoubleStrip’ has no member named ‘IsPositiveStrip’
   64 |   bool IsXStrip() const { return m_ReadOutElement->IsPositiveStrip(); }
      |                                                    ^~~~~~~~~~~~~~~
/mnt/y/SSL/COSI/COSItools/nuclearizer/include/MStripHit.h: In member function ‘void MStripHit::IsPositiveStrip(bool)’:
/mnt/y/SSL/COSI/COSItools/nuclearizer/include/MStripHit.h:67:64: error: ‘class MReadOutElementDoubleStrip’ has no member named ‘IsPositiveStrip’
   67 |   void IsPositiveStrip(bool PositiveStrip) { m_ReadOutElement->IsPositiveStrip(PositiveStrip); }
      |                                                                ^~~~~~~~~~~~~~~
/mnt/y/SSL/COSI/COSItools/nuclearizer/include/MStripHit.h: In member function ‘bool MStripHit::IsPositiveStrip() const’:
/mnt/y/SSL/COSI/COSItools/nuclearizer/include/MStripHit.h:69:59: error: ‘class MReadOutElementDoubleStrip’ has no member named ‘IsPositiveStrip’
   69 |   bool IsPositiveStrip() const { return m_ReadOutElement->IsPositiveStrip(); }
      |                                                           ^~~~~~~~~~~~~~~
In file included from /mnt/y/SSL/COSI/COSItools/nuclearizer/include/MReadOutAssembly.h:28,
                 from /mnt/y/SSL/COSI/COSItools/megalib/include/MModule.h:35,
                 from /mnt/y/SSL/COSI/COSItools/megalib/src/fretalon/framework/src/MGUIExpo.cxx:37:
/mnt/y/SSL/COSI/COSItools/nuclearizer/include/MStripHit.h: In member function ‘void MStripHit::IsXStrip(bool)’:
/mnt/y/SSL/COSI/COSItools/nuclearizer/include/MStripHit.h:62:57: error: ‘class MReadOutElementDoubleStrip’ has no member named ‘IsPositiveStrip’
   62 |   void IsXStrip(bool PositiveStrip) { m_ReadOutElement->IsPositiveStrip(PositiveStrip); }
      |                                                         ^~~~~~~~~~~~~~~
/mnt/y/SSL/COSI/COSItools/nuclearizer/include/MStripHit.h: In member function ‘bool MStripHit::IsXStrip() const’:
/mnt/y/SSL/COSI/COSItools/nuclearizer/include/MStripHit.h:64:52: error: ‘class MReadOutElementDoubleStrip’ has no member named ‘IsPositiveStrip’
   64 |   bool IsXStrip() const { return m_ReadOutElement->IsPositiveStrip(); }
      |                                                    ^~~~~~~~~~~~~~~
/mnt/y/SSL/COSI/COSItools/nuclearizer/include/MStripHit.h: In member function ‘void MStripHit::IsPositiveStrip(bool)’:
/mnt/y/SSL/COSI/COSItools/nuclearizer/include/MStripHit.h:67:64: error: ‘class MReadOutElementDoubleStrip’ has no member named ‘IsPositiveStrip’
   67 |   void IsPositiveStrip(bool PositiveStrip) { m_ReadOutElement->IsPositiveStrip(PositiveStrip); }
      |                                                                ^~~~~~~~~~~~~~~
/mnt/y/SSL/COSI/COSItools/nuclearizer/include/MStripHit.h: In member function ‘bool MStripHit::IsPositiveStrip() const’:
/mnt/y/SSL/COSI/COSItools/nuclearizer/include/MStripHit.h:69:59: error: ‘class MReadOutElementDoubleStrip’ has no member named ‘IsPositiveStrip’
   69 |   bool IsPositiveStrip() const { return m_ReadOutElement->IsPositiveStrip(); }
      |                                                           ^~~~~~~~~~~~~~~
make[1]: *** [Makefile:184: /mnt/y/SSL/COSI/COSItools/megalib/lib/MGUIEModule.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:184: /mnt/y/SSL/COSI/COSItools/megalib/lib/MGUIExpo.o] Error 1
In file included from /mnt/y/SSL/COSI/COSItools/nuclearizer/include/MReadOutAssembly.h:28,
                 from /mnt/y/SSL/COSI/COSItools/megalib/include/MModule.h:35,
                 from /mnt/y/SSL/COSI/COSItools/megalib/include/MGUIModuleSelector.h:33,
                 from /mnt/y/SSL/COSI/COSItools/megalib/src/fretalon/framework/src/MGUIModuleSelector.cxx:20:
/mnt/y/SSL/COSI/COSItools/nuclearizer/include/MStripHit.h: In member function ‘void MStripHit::IsXStrip(bool)’:
/mnt/y/SSL/COSI/COSItools/nuclearizer/include/MStripHit.h:62:57: error: ‘class MReadOutElementDoubleStrip’ has no member named ‘IsPositiveStrip’
   62 |   void IsXStrip(bool PositiveStrip) { m_ReadOutElement->IsPositiveStrip(PositiveStrip); }
      |                                                         ^~~~~~~~~~~~~~~
/mnt/y/SSL/COSI/COSItools/nuclearizer/include/MStripHit.h: In member function ‘bool MStripHit::IsXStrip() const’:
/mnt/y/SSL/COSI/COSItools/nuclearizer/include/MStripHit.h:64:52: error: ‘class MReadOutElementDoubleStrip’ has no member named ‘IsPositiveStrip’
   64 |   bool IsXStrip() const { return m_ReadOutElement->IsPositiveStrip(); }
      |                                                    ^~~~~~~~~~~~~~~
/mnt/y/SSL/COSI/COSItools/nuclearizer/include/MStripHit.h: In member function ‘void MStripHit::IsPositiveStrip(bool)’:
/mnt/y/SSL/COSI/COSItools/nuclearizer/include/MStripHit.h:67:64: error: ‘class MReadOutElementDoubleStrip’ has no member named ‘IsPositiveStrip’
   67 |   void IsPositiveStrip(bool PositiveStrip) { m_ReadOutElement->IsPositiveStrip(PositiveStrip); }
      |                                                                ^~~~~~~~~~~~~~~
/mnt/y/SSL/COSI/COSItools/nuclearizer/include/MStripHit.h: In member function ‘bool MStripHit::IsPositiveStrip() const’:
/mnt/y/SSL/COSI/COSItools/nuclearizer/include/MStripHit.h:69:59: error: ‘class MReadOutElementDoubleStrip’ has no member named ‘IsPositiveStrip’
   69 |   bool IsPositiveStrip() const { return m_ReadOutElement->IsPositiveStrip(); }
      |                                                           ^~~~~~~~~~~~~~~
In file included from /mnt/y/SSL/COSI/COSItools/nuclearizer/include/MReadOutAssembly.h:28,
                 from /mnt/y/SSL/COSI/COSItools/megalib/include/MModule.h:35,
                 from /mnt/y/SSL/COSI/COSItools/megalib/include/MGUIEModule.h:27,
                 from /mnt/y/SSL/COSI/COSItools/megalib/include/MGUIMainFretalon.h:33,
                 from /mnt/y/SSL/COSI/COSItools/megalib/src/fretalon/framework/src/MGUIMainFretalon.cxx:20:
/mnt/y/SSL/COSI/COSItools/nuclearizer/include/MStripHit.h: In member function ‘void MStripHit::IsXStrip(bool)’:
/mnt/y/SSL/COSI/COSItools/nuclearizer/include/MStripHit.h:62:57: error: ‘class MReadOutElementDoubleStrip’ has no member named ‘IsPositiveStrip’
   62 |   void IsXStrip(bool PositiveStrip) { m_ReadOutElement->IsPositiveStrip(PositiveStrip); }
      |                                                         ^~~~~~~~~~~~~~~
/mnt/y/SSL/COSI/COSItools/nuclearizer/include/MStripHit.h: In member function ‘bool MStripHit::IsXStrip() const’:
/mnt/y/SSL/COSI/COSItools/nuclearizer/include/MStripHit.h:64:52: error: ‘class MReadOutElementDoubleStrip’ has no member named ‘IsPositiveStrip’
   64 |   bool IsXStrip() const { return m_ReadOutElement->IsPositiveStrip(); }
      |                                                    ^~~~~~~~~~~~~~~
/mnt/y/SSL/COSI/COSItools/nuclearizer/include/MStripHit.h: In member function ‘void MStripHit::IsPositiveStrip(bool)’:
/mnt/y/SSL/COSI/COSItools/nuclearizer/include/MStripHit.h:67:64: error: ‘class MReadOutElementDoubleStrip’ has no member named ‘IsPositiveStrip’
   67 |   void IsPositiveStrip(bool PositiveStrip) { m_ReadOutElement->IsPositiveStrip(PositiveStrip); }
      |                                                                ^~~~~~~~~~~~~~~
/mnt/y/SSL/COSI/COSItools/nuclearizer/include/MStripHit.h: In member function ‘bool MStripHit::IsPositiveStrip() const’:
/mnt/y/SSL/COSI/COSItools/nuclearizer/include/MStripHit.h:69:59: error: ‘class MReadOutElementDoubleStrip’ has no member named ‘IsPositiveStrip’
   69 |   bool IsPositiveStrip() const { return m_ReadOutElement->IsPositiveStrip(); }
      |                                                           ^~~~~~~~~~~~~~~
make[1]: *** [Makefile:184: /mnt/y/SSL/COSI/COSItools/megalib/lib/MGUIModuleSelector.o] Error 1
make[1]: *** [Makefile:184: /mnt/y/SSL/COSI/COSItools/megalib/lib/MGUIMainFretalon.o] Error 1
make[1]: Leaving directory '/mnt/y/SSL/COSI/COSItools/nuclearizer'
make: *** [Makefile:154: all] Error 2
ERROR: Something went wrong while compiling MEGAlib!
`

**Comment by zoglauer** [comment]
Fixed in nuclearizer
