### ISSUE TITLE
Installation cannot complete -- dead link to Geant4 repo

### ISSUE THREAD

**Issue by mikemoss3** [cositools/cosi-setup#4]
Hello, 

I am trying to install COSItools, but I am unable to complete installation because the installer attempts to download Geant4 files from dead links. Here are two examples of the dead links in question: 
http://geant4.cern.ch/support/source/G4RadioactiveDecay.4.3.2.tar.gz
https://geant4.web.cern.ch/support/source/G4ABLA.3.0.tar.gz 

Do you know what the updated links should be and how I can edit the installer to use the new links?

Best,
Mike Moss

**Comment by zoglauer** [comment]
Hi Mike,

Can you try again? Because I just tried and it works. But I have in the past experienced that part of the cern website are down for a few hours / even days and then it did not work for a while.

Best,
Andreas

**Comment by zoglauer** [comment]
Btw, did you use the installer from the main branch? That's the recommended one now.

**Comment by mikemoss3** [comment]
Hi Andreas,

I just tried again and I'm still seeing that the files cannot be downloaded. Clicking on the link also still shows me "404 Page Not Found". 

I think I'm running from the main branch(?). I am running running the command found in the COSItools README:
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/cositools/cosi-setup/feature/initialsetup/setup.sh)" --extras=cosi-data-challenge-1

**Comment by zoglauer** [comment]
That's the main branch:
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/cositools/cosi-setup/main/setup.sh)" _ --extras=cosi-data-challenge-1

**Comment by mikemoss3** [comment]
Hi Andreas, 

That looks like it did the trick. I guess I really wasn't on the main branch. 
The README on the COSI data challenge github has a link to the feature branch. Is that incorrect? Should I open up an issue on the data challenge github?

Thanks a bunch, 
Mike Moss

**Comment by zoglauer** [comment]
Thanks, I just merged the changes from main back into the feature branch. Thus the feature branch should work again.

**Comment by mikemoss3** [comment]
Ok, sounds great. I'll close the issue. 
Thank you again, Andreas.
