### ISSUE TITLE
Virtual Python Environment pyyaml Setup 

### ISSUE THREAD

**Issue by avalluvan** [cositools/cosi-setup#6]
Executing the following file may fail due to a Cython conflict: [setup-python3.sh](https://github.com/cositools/cosi-setup/blob/main/setup-python3.sh)

As posted on the cosi-data-challenges repository (see https://github.com/cositools/cosi-data-challenges/issues/65), changing the requirements.txt file will work.

**Comment by zoglauer** [comment]
cost-setup just pulls from the included libraries. Since it is fixed in the underlying library. It is fixed here to.
